# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = {
  'primary' => { 'ip' => '10.10.10.20', 'memory' => '2048', 'cpus' => '2' },
  'secondary' => { 'ip' => '10.10.10.21', 'memory' => '2048', 'cpus' => '2' }
}

Vagrant.configure("2") do |config|

  servers.each do |name, conf|
    config.vm.define "#{name}" do |cfg|
      cfg.vm.box = "centos-base-image"
      cfg.vm.box_version = "20200225.0.0"
      cfg.vm.box_url = "file:///data/Backup/Vagrant/Boxes/centos-base-image/centos-base-image.json"
      cfg.vm.box_check_update = true
      cfg.vm.hostname = "#{name}.meudominio.local"
      cfg.vm.network "private_network", ip: "#{conf['ip']}"
      cfg.vm.provision :hosts, :sync_hosts => true

      cfg.vbguest.auto_update = false

      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.gui = false
        vb.cpus = "#{conf['cpus']}"
        vb.memory = "#{conf['memory']}"
      end

      cfg.vm.provision "shell", inline: <<-SHELL
        hostnamectl
      SHELL
    end
  end
end